# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ArchivosUi/VentanaOpcionesProductosGui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VentanaOpcionesProductosGui(object):
    def setupUi(self, VentanaOpcionesProductosGui):
        VentanaOpcionesProductosGui.setObjectName("VentanaOpcionesProductosGui")
        VentanaOpcionesProductosGui.resize(463, 406)
        VentanaOpcionesProductosGui.setMinimumSize(QtCore.QSize(463, 406))
        VentanaOpcionesProductosGui.setMaximumSize(QtCore.QSize(463, 406))
        VentanaOpcionesProductosGui.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.centralwidget = QtWidgets.QWidget(VentanaOpcionesProductosGui)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtACodigoBarra = QtWidgets.QLineEdit(self.centralwidget)
        self.txtACodigoBarra.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtACodigoBarra.setObjectName("txtACodigoBarra")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtACodigoBarra)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtANombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtANombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtANombre.setObjectName("txtANombre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtANombre)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.textEditADescripcion = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditADescripcion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditADescripcion.setObjectName("textEditADescripcion")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textEditADescripcion)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.stockspink = QtWidgets.QSpinBox(self.centralwidget)
        self.stockspink.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stockspink.setMaximum(1000)
        self.stockspink.setObjectName("stockspink")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.stockspink)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.preciospin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.preciospin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.preciospin.setMaximum(999999.99)
        self.preciospin.setObjectName("preciospin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.preciospin)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboMarca = QtWidgets.QComboBox(self.centralwidget)
        self.comboMarca.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 87, 83);")
        self.comboMarca.setObjectName("comboMarca")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboMarca)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpdate.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"")
        self.btnUpdate.setObjectName("btnUpdate")
        self.horizontalLayout_2.addWidget(self.btnUpdate)
        self.btnEliminar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEliminar.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.btnEliminar.setObjectName("btnEliminar")
        self.horizontalLayout_2.addWidget(self.btnEliminar)
        self.btnACancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnACancelar.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.btnACancelar.setObjectName("btnACancelar")
        self.horizontalLayout_2.addWidget(self.btnACancelar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        VentanaOpcionesProductosGui.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(VentanaOpcionesProductosGui)
        self.statusbar.setObjectName("statusbar")
        VentanaOpcionesProductosGui.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaOpcionesProductosGui)
        QtCore.QMetaObject.connectSlotsByName(VentanaOpcionesProductosGui)

    def retranslateUi(self, VentanaOpcionesProductosGui):
        _translate = QtCore.QCoreApplication.translate
        VentanaOpcionesProductosGui.setWindowTitle(_translate("VentanaOpcionesProductosGui", "Opciones Producto"))
        self.label.setText(_translate("VentanaOpcionesProductosGui", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">AGREGAR PRODUCTOS</span></p></body></html>"))
        self.label_3.setText(_translate("VentanaOpcionesProductosGui", "CodigoBarra:"))
        self.label_4.setText(_translate("VentanaOpcionesProductosGui", "Nombre"))
        self.label_5.setText(_translate("VentanaOpcionesProductosGui", "Descripcion"))
        self.label_6.setText(_translate("VentanaOpcionesProductosGui", "Stock:"))
        self.label_7.setText(_translate("VentanaOpcionesProductosGui", "Precio:"))
        self.label_8.setText(_translate("VentanaOpcionesProductosGui", "Marca"))
        self.btnUpdate.setText(_translate("VentanaOpcionesProductosGui", "Actualizar"))
        self.btnEliminar.setText(_translate("VentanaOpcionesProductosGui", "Eliminar"))
        self.btnACancelar.setText(_translate("VentanaOpcionesProductosGui", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaOpcionesProductosGui = QtWidgets.QMainWindow()
    ui = Ui_VentanaOpcionesProductosGui()
    ui.setupUi(VentanaOpcionesProductosGui)
    VentanaOpcionesProductosGui.show()
    sys.exit(app.exec_())

