# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ArchivosUi/VentanaAgregarProductosGui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VentanaAgregarProductosGui(object):
    def setupUi(self, VentanaAgregarProductosGui):
        VentanaAgregarProductosGui.setObjectName("VentanaAgregarProductosGui")
        VentanaAgregarProductosGui.resize(463, 406)
        VentanaAgregarProductosGui.setMinimumSize(QtCore.QSize(463, 406))
        VentanaAgregarProductosGui.setMaximumSize(QtCore.QSize(463, 406))
        VentanaAgregarProductosGui.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.centralwidget = QtWidgets.QWidget(VentanaAgregarProductosGui)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtACodigoBarra = QtWidgets.QLineEdit(self.centralwidget)
        self.txtACodigoBarra.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtACodigoBarra.setObjectName("txtACodigoBarra")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtACodigoBarra)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtANombre = QtWidgets.QLineEdit(self.centralwidget)
        self.txtANombre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtANombre.setObjectName("txtANombre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtANombre)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.textEditADescripcion = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditADescripcion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditADescripcion.setObjectName("textEditADescripcion")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textEditADescripcion)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.stockspink = QtWidgets.QSpinBox(self.centralwidget)
        self.stockspink.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stockspink.setMaximum(1000)
        self.stockspink.setObjectName("stockspink")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.stockspink)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.preciospin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.preciospin.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.preciospin.setMaximum(999999.99)
        self.preciospin.setObjectName("preciospin")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.preciospin)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboMarca = QtWidgets.QComboBox(self.centralwidget)
        self.comboMarca.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 87, 83);")
        self.comboMarca.setObjectName("comboMarca")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboMarca)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAAgregar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAAgregar.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"")
        self.btnAAgregar.setObjectName("btnAAgregar")
        self.horizontalLayout_2.addWidget(self.btnAAgregar)
        self.btnACancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnACancelar.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.btnACancelar.setObjectName("btnACancelar")
        self.horizontalLayout_2.addWidget(self.btnACancelar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        VentanaAgregarProductosGui.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(VentanaAgregarProductosGui)
        self.statusbar.setObjectName("statusbar")
        VentanaAgregarProductosGui.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaAgregarProductosGui)
        QtCore.QMetaObject.connectSlotsByName(VentanaAgregarProductosGui)

    def retranslateUi(self, VentanaAgregarProductosGui):
        _translate = QtCore.QCoreApplication.translate
        VentanaAgregarProductosGui.setWindowTitle(_translate("VentanaAgregarProductosGui", "Agregar Producto"))
        self.label.setText(_translate("VentanaAgregarProductosGui", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">AGREGAR PRODUCTOS</span></p></body></html>"))
        self.label_3.setText(_translate("VentanaAgregarProductosGui", "CodigoBarra:"))
        self.label_4.setText(_translate("VentanaAgregarProductosGui", "Nombre"))
        self.label_5.setText(_translate("VentanaAgregarProductosGui", "Descripcion"))
        self.label_6.setText(_translate("VentanaAgregarProductosGui", "Stock:"))
        self.label_7.setText(_translate("VentanaAgregarProductosGui", "Precio:"))
        self.label_8.setText(_translate("VentanaAgregarProductosGui", "Marca"))
        self.btnAAgregar.setText(_translate("VentanaAgregarProductosGui", "Agregar"))
        self.btnACancelar.setText(_translate("VentanaAgregarProductosGui", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaAgregarProductosGui = QtWidgets.QMainWindow()
    ui = Ui_VentanaAgregarProductosGui()
    ui.setupUi(VentanaAgregarProductosGui)
    VentanaAgregarProductosGui.show()
    sys.exit(app.exec_())

