# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ArchivosUi/VentanaPricipalGui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VentanaPricipal(object):
    def setupUi(self, VentanaPricipal):
        VentanaPricipal.setObjectName("VentanaPricipal")
        VentanaPricipal.resize(1112, 546)
        VentanaPricipal.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.centralwidget = QtWidgets.QWidget(VentanaPricipal)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("font: 75 20pt \"URW Bookman L\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtBusquedaProductos = QtWidgets.QLineEdit(self.centralwidget)
        self.txtBusquedaProductos.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0199005 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.txtBusquedaProductos.setObjectName("txtBusquedaProductos")
        self.verticalLayout.addWidget(self.txtBusquedaProductos)
        self.tablaProductos = QtWidgets.QTableWidget(self.centralwidget)
        self.tablaProductos.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(238, 238, 236);")
        self.tablaProductos.setObjectName("tablaProductos")
        self.tablaProductos.setColumnCount(5)
        self.tablaProductos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductos.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tablaProductos)
        self.btnExportar = QtWidgets.QPushButton(self.centralwidget)
        self.btnExportar.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"")
        self.btnExportar.setObjectName("btnExportar")
        self.verticalLayout.addWidget(self.btnExportar)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btnAddProducto = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddProducto.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/BotonesCentrales/Recursos/Mas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddProducto.setIcon(icon)
        self.btnAddProducto.setIconSize(QtCore.QSize(30, 30))
        self.btnAddProducto.setObjectName("btnAddProducto")
        self.verticalLayout_2.addWidget(self.btnAddProducto)
        self.btnQuitarProducto = QtWidgets.QPushButton(self.centralwidget)
        self.btnQuitarProducto.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/BotonesCentrales/Recursos/Menos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnQuitarProducto.setIcon(icon1)
        self.btnQuitarProducto.setIconSize(QtCore.QSize(30, 30))
        self.btnQuitarProducto.setObjectName("btnQuitarProducto")
        self.verticalLayout_2.addWidget(self.btnQuitarProducto)
        self.btnBloquear = QtWidgets.QPushButton(self.centralwidget)
        self.btnBloquear.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/BotonesCentrales/Recursos/Candado.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBloquear.setIcon(icon2)
        self.btnBloquear.setIconSize(QtCore.QSize(30, 30))
        self.btnBloquear.setObjectName("btnBloquear")
        self.verticalLayout_2.addWidget(self.btnBloquear)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("color: rgb(238, 238, 236);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.txtPrecioFinal = QtWidgets.QLabel(self.centralwidget)
        self.txtPrecioFinal.setStyleSheet("color: rgb(238, 238, 236);")
        self.txtPrecioFinal.setObjectName("txtPrecioFinal")
        self.gridLayout.addWidget(self.txtPrecioFinal, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.txtIva = QtWidgets.QLabel(self.centralwidget)
        self.txtIva.setStyleSheet("color: rgb(238, 238, 236);")
        self.txtIva.setObjectName("txtIva")
        self.gridLayout.addWidget(self.txtIva, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tablaProductosVenta = QtWidgets.QTableWidget(self.centralwidget)
        self.tablaProductosVenta.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"color: rgb(238, 238, 236);")
        self.tablaProductosVenta.setObjectName("tablaProductosVenta")
        self.tablaProductosVenta.setColumnCount(5)
        self.tablaProductosVenta.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductosVenta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductosVenta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductosVenta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductosVenta.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaProductosVenta.setHorizontalHeaderItem(4, item)
        self.verticalLayout_3.addWidget(self.tablaProductosVenta)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnPago = QtWidgets.QPushButton(self.centralwidget)
        self.btnPago.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"")
        self.btnPago.setObjectName("btnPago")
        self.horizontalLayout_2.addWidget(self.btnPago)
        self.btnCancelarPago = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelarPago.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.btnCancelarPago.setObjectName("btnCancelarPago")
        self.horizontalLayout_2.addWidget(self.btnCancelarPago)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        VentanaPricipal.setCentralWidget(self.centralwidget)
        self.BarraMenu = QtWidgets.QMenuBar(VentanaPricipal)
        self.BarraMenu.setGeometry(QtCore.QRect(0, 0, 1112, 31))
        self.BarraMenu.setStyleSheet("font: 75 16pt \"URW Bookman L\";\n"
"\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"selection-background-color: rgb(52, 101, 164);")
        self.BarraMenu.setObjectName("BarraMenu")
        self.menuAyuda = QtWidgets.QMenu(self.BarraMenu)
        self.menuAyuda.setStyleSheet("font: 75 14pt \"URW Bookman L\";\n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(52, 101, 164);")
        self.menuAyuda.setObjectName("menuAyuda")
        self.menuAlta = QtWidgets.QMenu(self.BarraMenu)
        self.menuAlta.setStyleSheet("color: rgb(255, 255, 255);")
        self.menuAlta.setObjectName("menuAlta")
        self.menualta = QtWidgets.QMenu(self.menuAlta)
        self.menualta.setStyleSheet("color: rgb(255, 255, 255);")
        self.menualta.setObjectName("menualta")
        self.menuHerramientas = QtWidgets.QMenu(self.BarraMenu)
        self.menuHerramientas.setStyleSheet("\n"
"font: 75 14pt \"URW Bookman L\";\n"
"color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(52, 101, 164);")
        self.menuHerramientas.setObjectName("menuHerramientas")
        VentanaPricipal.setMenuBar(self.BarraMenu)
        self.statusbar = QtWidgets.QStatusBar(VentanaPricipal)
        self.statusbar.setObjectName("statusbar")
        VentanaPricipal.setStatusBar(self.statusbar)
        self.actionAcerca_de = QtWidgets.QAction(VentanaPricipal)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionDocumentacion = QtWidgets.QAction(VentanaPricipal)
        self.actionDocumentacion.setObjectName("actionDocumentacion")
        self.actionEscanerApp = QtWidgets.QAction(VentanaPricipal)
        self.actionEscanerApp.setObjectName("actionEscanerApp")
        self.actionproductoalta = QtWidgets.QAction(VentanaPricipal)
        self.actionproductoalta.setObjectName("actionproductoalta")
        self.actionMarcaalta = QtWidgets.QAction(VentanaPricipal)
        self.actionMarcaalta.setObjectName("actionMarcaalta")
        self.actionEliminar = QtWidgets.QAction(VentanaPricipal)
        self.actionEliminar.setObjectName("actionEliminar")
        self.actionProductos = QtWidgets.QAction(VentanaPricipal)
        self.actionProductos.setObjectName("actionProductos")
        self.actionMarcas = QtWidgets.QAction(VentanaPricipal)
        self.actionMarcas.setObjectName("actionMarcas")
        self.actionUsuarios = QtWidgets.QAction(VentanaPricipal)
        self.actionUsuarios.setObjectName("actionUsuarios")
        self.actionCategoriasalta = QtWidgets.QAction(VentanaPricipal)
        self.actionCategoriasalta.setObjectName("actionCategoriasalta")
        self.actionProveedor = QtWidgets.QAction(VentanaPricipal)
        self.actionProveedor.setObjectName("actionProveedor")
        self.actionEmpleado = QtWidgets.QAction(VentanaPricipal)
        self.actionEmpleado.setObjectName("actionEmpleado")
        self.actionIva = QtWidgets.QAction(VentanaPricipal)
        self.actionIva.setObjectName("actionIva")
        self.menuAyuda.addAction(self.actionAcerca_de)
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.actionDocumentacion)
        self.menuAyuda.addSeparator()
        self.menualta.addAction(self.actionproductoalta)
        self.menualta.addAction(self.actionMarcaalta)
        self.menualta.addAction(self.actionProveedor)
        self.menualta.addAction(self.actionEmpleado)
        self.menualta.addAction(self.actionIva)
        self.menuAlta.addAction(self.menualta.menuAction())
        self.menuHerramientas.addAction(self.actionEscanerApp)
        self.menuHerramientas.addSeparator()
        self.BarraMenu.addAction(self.menuAlta.menuAction())
        self.BarraMenu.addAction(self.menuHerramientas.menuAction())
        self.BarraMenu.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(VentanaPricipal)
        QtCore.QMetaObject.connectSlotsByName(VentanaPricipal)

    def retranslateUi(self, VentanaPricipal):
        _translate = QtCore.QCoreApplication.translate
        VentanaPricipal.setWindowTitle(_translate("VentanaPricipal", "PuntoDeVenta"))
        self.label.setText(_translate("VentanaPricipal", "Productos"))
        item = self.tablaProductos.horizontalHeaderItem(0)
        item.setText(_translate("VentanaPricipal", "ID"))
        item = self.tablaProductos.horizontalHeaderItem(1)
        item.setText(_translate("VentanaPricipal", "Nombre"))
        item = self.tablaProductos.horizontalHeaderItem(2)
        item.setText(_translate("VentanaPricipal", "Stock"))
        item = self.tablaProductos.horizontalHeaderItem(3)
        item.setText(_translate("VentanaPricipal", "Precio"))
        item = self.tablaProductos.horizontalHeaderItem(4)
        item.setText(_translate("VentanaPricipal", "Detalles"))
        self.btnExportar.setText(_translate("VentanaPricipal", "Exportar"))
        self.label_2.setText(_translate("VentanaPricipal", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Venta</span></p></body></html>"))
        self.label_4.setText(_translate("VentanaPricipal", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Total</span></p></body></html>"))
        self.txtPrecioFinal.setText(_translate("VentanaPricipal", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">-------------</span></p></body></html>"))
        self.label_3.setText(_translate("VentanaPricipal", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">IVA</span></p></body></html>"))
        self.txtIva.setText(_translate("VentanaPricipal", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">-------------</span></p></body></html>"))
        item = self.tablaProductosVenta.horizontalHeaderItem(0)
        item.setText(_translate("VentanaPricipal", "ID"))
        item = self.tablaProductosVenta.horizontalHeaderItem(1)
        item.setText(_translate("VentanaPricipal", "Nombre"))
        item = self.tablaProductosVenta.horizontalHeaderItem(2)
        item.setText(_translate("VentanaPricipal", "Cantidad"))
        item = self.tablaProductosVenta.horizontalHeaderItem(3)
        item.setText(_translate("VentanaPricipal", "Precio Venta"))
        item = self.tablaProductosVenta.horizontalHeaderItem(4)
        item.setText(_translate("VentanaPricipal", "Precio Total"))
        self.btnPago.setText(_translate("VentanaPricipal", "Pago"))
        self.btnCancelarPago.setText(_translate("VentanaPricipal", "Cancelar Compra"))
        self.menuAyuda.setTitle(_translate("VentanaPricipal", "Ayuda"))
        self.menuAlta.setTitle(_translate("VentanaPricipal", "BD"))
        self.menualta.setTitle(_translate("VentanaPricipal", "Alta"))
        self.menuHerramientas.setTitle(_translate("VentanaPricipal", "Herramientas"))
        self.actionAcerca_de.setText(_translate("VentanaPricipal", "Acerca de"))
        self.actionDocumentacion.setText(_translate("VentanaPricipal", "Documentacion"))
        self.actionEscanerApp.setText(_translate("VentanaPricipal", "EscanerApp"))
        self.actionproductoalta.setText(_translate("VentanaPricipal", "Productos"))
        self.actionMarcaalta.setText(_translate("VentanaPricipal", "Marca"))
        self.actionEliminar.setText(_translate("VentanaPricipal", "Eliminar"))
        self.actionProductos.setText(_translate("VentanaPricipal", "Productos"))
        self.actionMarcas.setText(_translate("VentanaPricipal", "Marcas"))
        self.actionUsuarios.setText(_translate("VentanaPricipal", "Usuarios"))
        self.actionCategoriasalta.setText(_translate("VentanaPricipal", "Categorias"))
        self.actionProveedor.setText(_translate("VentanaPricipal", "Proveedor"))
        self.actionEmpleado.setText(_translate("VentanaPricipal", "Empleado"))
        self.actionIva.setText(_translate("VentanaPricipal", "Iva"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaPricipal = QtWidgets.QMainWindow()
    ui = Ui_VentanaPricipal()
    ui.setupUi(VentanaPricipal)
    VentanaPricipal.show()
    sys.exit(app.exec_())

