# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ArchivosUi/VentanaAgregarProvedor.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VentanaAgregarProveedorGui(object):
    def setupUi(self, VentanaAgregarProveedorGui):
        VentanaAgregarProveedorGui.setObjectName("VentanaAgregarProveedorGui")
        VentanaAgregarProveedorGui.resize(463, 406)
        VentanaAgregarProveedorGui.setMinimumSize(QtCore.QSize(463, 406))
        VentanaAgregarProveedorGui.setMaximumSize(QtCore.QSize(463, 406))
        VentanaAgregarProveedorGui.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.centralwidget = QtWidgets.QWidget(VentanaAgregarProveedorGui)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txtCompania = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCompania.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCompania.setObjectName("txtCompania")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtCompania)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtContacto = QtWidgets.QLineEdit(self.centralwidget)
        self.txtContacto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtContacto.setObjectName("txtContacto")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtContacto)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.txtDireccion = QtWidgets.QLineEdit(self.centralwidget)
        self.txtDireccion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtDireccion.setObjectName("txtDireccion")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtDireccion)
        self.txtCiudad = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCiudad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCiudad.setObjectName("txtCiudad")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtCiudad)
        self.txtRegion = QtWidgets.QLineEdit(self.centralwidget)
        self.txtRegion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtRegion.setObjectName("txtRegion")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtRegion)
        self.txtCodigoPostal = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCodigoPostal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtCodigoPostal.setObjectName("txtCodigoPostal")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtCodigoPostal)
        self.txtPais = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPais.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtPais.setObjectName("txtPais")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txtPais)
        self.txtTelefono = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTelefono.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtTelefono.setObjectName("txtTelefono")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txtTelefono)
        self.txtFax = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFax.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtFax.setObjectName("txtFax")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.txtFax)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAAgregar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAAgregar.setStyleSheet("background-color: rgb(136, 138, 133);\n"
"")
        self.btnAAgregar.setObjectName("btnAAgregar")
        self.horizontalLayout_2.addWidget(self.btnAAgregar)
        self.btnACancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnACancelar.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.btnACancelar.setObjectName("btnACancelar")
        self.horizontalLayout_2.addWidget(self.btnACancelar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        VentanaAgregarProveedorGui.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(VentanaAgregarProveedorGui)
        self.statusbar.setObjectName("statusbar")
        VentanaAgregarProveedorGui.setStatusBar(self.statusbar)

        self.retranslateUi(VentanaAgregarProveedorGui)
        QtCore.QMetaObject.connectSlotsByName(VentanaAgregarProveedorGui)

    def retranslateUi(self, VentanaAgregarProveedorGui):
        _translate = QtCore.QCoreApplication.translate
        VentanaAgregarProveedorGui.setWindowTitle(_translate("VentanaAgregarProveedorGui", "Agregar Producto"))
        self.label.setText(_translate("VentanaAgregarProveedorGui", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">AGREGAR PROVEDOR</span></p></body></html>"))
        self.label_3.setText(_translate("VentanaAgregarProveedorGui", "Compañia:"))
        self.label_4.setText(_translate("VentanaAgregarProveedorGui", "Contacto"))
        self.label_2.setText(_translate("VentanaAgregarProveedorGui", "Direccion:"))
        self.label_5.setText(_translate("VentanaAgregarProveedorGui", "Ciudad:"))
        self.label_6.setText(_translate("VentanaAgregarProveedorGui", "Region:"))
        self.label_7.setText(_translate("VentanaAgregarProveedorGui", "Codigo Postal:"))
        self.label_8.setText(_translate("VentanaAgregarProveedorGui", "Pais:"))
        self.label_9.setText(_translate("VentanaAgregarProveedorGui", "Telefono:"))
        self.label_10.setText(_translate("VentanaAgregarProveedorGui", "Fax:"))
        self.btnAAgregar.setText(_translate("VentanaAgregarProveedorGui", "Agregar"))
        self.btnACancelar.setText(_translate("VentanaAgregarProveedorGui", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VentanaAgregarProveedorGui = QtWidgets.QMainWindow()
    ui = Ui_VentanaAgregarProveedorGui()
    ui.setupUi(VentanaAgregarProveedorGui)
    VentanaAgregarProveedorGui.show()
    sys.exit(app.exec_())

